# Generated by Django 4.2.7 on 2024-06-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lab', models.CharField(max_length=30)),
                ('Admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labs.usermanage')),
            ],
        ),
    ]
