# Generated by Django 4.2.7 on 2024-06-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanage',
            name='status',
        ),
        migrations.AddField(
            model_name='usermanage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
