# Generated by Django 4.2.7 on 2024-06-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_remove_usermanage_status_usermanage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='status',
            field=models.CharField(default='disable', max_length=20),
        ),
    ]
