# Generated by Django 5.0.6 on 2024-07-25 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_remove_usermanage_is_admin_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='lab_name',
            field=models.ForeignKey(limit_choices_to={'is_lab': True}, on_delete=django.db.models.deletion.CASCADE, related_name='labs', to=settings.AUTH_USER_MODEL),
        ),
    ]
