# Generated by Django 4.2.7 on 2024-06-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_usermanage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanage',
            name='is_active',
        ),
    ]
