# Generated by Django 5.0.6 on 2024-07-25 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_alter_doctor_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='lab',
            field=models.ForeignKey(limit_choices_to={'is_lab': True}, on_delete=django.db.models.deletion.CASCADE, related_name='res_lab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='lab',
            field=models.ForeignKey(limit_choices_to={'is_lab': True}, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
