# Generated by Django 4.2.7 on 2024-06-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_remove_usermanage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
