# Generated by Django 4.2.7 on 2024-06-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_usermanage_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermanage',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usermanage',
            name='status',
        ),
    ]
