# Generated by Django 4.2.7 on 2024-06-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_remove_usermanage_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='usermanage',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermanage',
            name='status',
            field=models.CharField(default='enable', max_length=20),
        ),
    ]
