# Generated by Django 4.2.7 on 2024-06-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_usermanage_is_active_usermanage_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='status',
            field=models.CharField(default='disable', max_length=20),
        ),
    ]
