# Generated by Django 5.0.7 on 2024-08-05 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_testreview_testreviewreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreviewreply',
            name='lab_admin',
            field=models.ForeignKey(limit_choices_to={'is_lab': True}, on_delete=django.db.models.deletion.CASCADE, related_name='review_reply', to=settings.AUTH_USER_MODEL),
        ),
    ]
