# Generated by Django 4.2.7 on 2024-06-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0009_alter_usermanage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages', models.CharField(blank=True, max_length=20, null=True)),
                ('test', models.CharField(blank=True, max_length=20, null=True)),
                ('doctors', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
