# Generated by Django 4.2.7 on 2024-06-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0010_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.CharField(blank=True, max_length=20, null=True)),
                ('tests', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('packageimage', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='lab',
        ),
    ]
