# Generated by Django 5.0 on 2024-06-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0011_package_delete_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='packageimage',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('testprice', models.IntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='labs.package')),
            ],
        ),
    ]
