# Generated by Django 5.0 on 2024-06-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0012_alter_package_packageimage_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('specialiazation', models.CharField(max_length=20)),
                ('doctorimage', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
