# Generated by Django 5.0.7 on 2024-08-31 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0013_remove_reservation_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='user',
        ),
        migrations.AddField(
            model_name='testresult',
            name='reservation',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='labs.reservation'),
            preserve_default=False,
        ),
    ]
