# Generated by Django 5.0 on 2024-06-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0013_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
    ]
