# Generated by Django 5.0.7 on 2024-09-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0014_remove_testresult_test_remove_testresult_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='testname',
            field=models.CharField(max_length=255),
        ),
    ]
